port: 7890
socks-port: 7891
redir-port: 0
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:6152'
secret: ''
Proxy:
 - { name: "httpxx", type: http, server: 127.0.0.1, port: 443 }
Proxy Group:
- { name: "auto", type: url-test, proxies: ["httpxx"], url: "https://www.bing.com", interval: 300 }
- { name: "fallback-auto", type: fallback, proxies: ["httpxx"], url: "https://www.bing.com", interval: 300 }
- { name: "Proxy", type: select, proxies: ["httpxx", "auto"] }

Rule:
- IP-CIDR,127.0.0.0/8,DIRECT
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,firstshare.cn,DIRECT
- DOMAIN-SUFFIX,foneshare.cn,DIRECT
- DOMAIN-SUFFIX,ceshi112.com,DIRECT
- DOMAIN-SUFFIX,ceshi113.com,DIRECT
- DOMAIN-SUFFIX,fxiaoke.com,DIRECT
#- DOMAIN,e.crashlytics.com,REJECT //注释此选项有助于大多数App开发者分析崩溃信息；如果您拒绝一切崩溃数据统计、搜集，请取消 # 注释。


# 自定义规则
## 您可以在此处插入您补充的自定义规则
# LAN
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT

# 最终规则
- GEOIP,CN,DIRECT
- MATCH,Proxy
