Rule:
- IP-CIDR,127.0.0.0/8,DIRECT
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,firstshare.cn,DIRECT
- DOMAIN-SUFFIX,foneshare.cn,DIRECT
- DOMAIN-SUFFIX,ceshi112.com,DIRECT
- DOMAIN-SUFFIX,ceshi113.com,DIRECT
- DOMAIN-SUFFIX,fxiaoke.com,DIRECT